name: Automated Testing Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  php-tests:
    name: PHP Unit & Integration Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, json, tokenizer, curl
        
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-dev
      
    - name: Run PHP Test Suite
      run: |
        mkdir -p tests/results
        # テスト用の設定ファイルを作成
        echo '{}' > api_keys.json
        php tests/run_all_tests.php || true
        
    - name: Upload PHP Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: php-test-results
        path: tests/results/
        
  e2e-tests:
    name: E2E Quick Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check E2E Test Availability
      id: check_e2e
      run: |
        if [ -d "tests/e2e" ] && [ -f "tests/e2e/requirements.txt" ]; then
          echo "e2e_available=true" >> $GITHUB_OUTPUT
        else
          echo "e2e_available=false" >> $GITHUB_OUTPUT
          echo "E2E tests not available - tests directory excluded from deployment"
        fi
    
    - name: Setup PHP
      if: steps.check_e2e.outputs.e2e_available == 'true'
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        
    - name: Setup Python
      if: steps.check_e2e.outputs.e2e_available == 'true'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install E2E Test Dependencies
      if: steps.check_e2e.outputs.e2e_available == 'true'
      run: |
        cd tests/e2e
        pip install -r requirements.txt
        
    - name: Start PHP Server
      if: steps.check_e2e.outputs.e2e_available == 'true'
      run: |
        php -S localhost:8000 &
        sleep 3
        
    - name: Run E2E Quick Tests
      if: steps.check_e2e.outputs.e2e_available == 'true'
      run: |
        cd tests/e2e
        mkdir -p logs
        python3 run_quick_tests.py || true
        
    - name: Create E2E Skip Log
      if: steps.check_e2e.outputs.e2e_available == 'false'
      run: |
        mkdir -p tests/e2e/logs
        echo "E2E tests skipped - tests directory not available in deployment" > tests/e2e/logs/skipped.log
        
    - name: Upload E2E Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-results
        path: tests/e2e/logs/
        
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Security Analysis
      run: |
        # Use improved security check script
        chmod +x .github/scripts/security-check.sh
        .github/scripts/security-check.sh
        
  comprehensive-test:
    name: Comprehensive Test Suite
    runs-on: ubuntu-latest
    needs: [php-tests, e2e-tests]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Dependencies
      run: |
        composer install --prefer-dist --no-progress --no-dev
        cd tests/e2e
        pip install -r requirements.txt
        
    - name: Run Comprehensive Test Suite
      run: |
        if [ -f "tests/run_test_suite.sh" ]; then
          chmod +x tests/run_test_suite.sh
          tests/run_test_suite.sh || true
        else
          echo "Comprehensive test suite not available, running basic PHP tests only"
          mkdir -p tests/results
          echo '{}' > api_keys.json
          php tests/run_all_tests.php || true
        fi
        
    - name: Upload Comprehensive Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: comprehensive-test-results
        path: tests/results/